name: Minted CDK Observability CI/CD

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGION: ap-southeast-1 # Deployment Region
  THE_AWS_KEY_ID: ${{ secrets.TOOLS_MSTA_ACCOUNT_ACCESS_KEY_ID }}
  THE_AWS_ACCESS_KEY: ${{ secrets.TOOLS_MSTA_ACCOUNT_SECRET_ACCESS_KEY }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  plan:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        aws-env: [mdev, msta, mpro]
        include:
          - aws-env: mdev
          - aws-env: msta
          - aws-env: mpro

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Sets up AWS profile.
      - name: Configure msta AWS credentials
        if: ${{ matrix.aws-env }} == 'mdev' || ${{ matrix.aws-env }} == 'msta'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TOOLS_MSTA_ACCOUNT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TOOLS_MSTA_ACCOUNT_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-duration-seconds: 1200
          role-session-name: GitActionDeploymentSession
          #role-to-assume: ${{ secrets.CROSS_ACCOUNT_ROLE }}
      - name: Configure mpro AWS credentials
        if: ${{ matrix.aws-env }} == 'mdev' || ${{ matrix.aws-env }} == 'msta'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TOOLS_MSTA_ACCOUNT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TOOLS_MSTA_ACCOUNT_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-duration-seconds: 1200
          role-session-name: GitActionDeploymentSession

      # Installs CDK and other prerequisites
      - name: Prerequisite Installation
        run: |
          sudo npm install -g aws-cdk@2.33.0
          cdk --version
          aws s3 ls
          npm install
      - name: plan-${{ matrix.aws-env }}
        run: |
          npm run build
          cdk diff 