name: Minted CDK Observability CI/CD

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGION: ap-southeast-1 # Deployment Region
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws-env: [mdev, msta, mpro]
        include:
          - aws-env: mdev
            aws-acc: msta
          - aws-env: msta
            aws-acc: msta
          - aws-env: mpro
            aws-acc: mpro
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Sets up AWS profile.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TOOLS_ACCOUNT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TOOLS_ACCOUNT_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-duration-seconds: 1200
          role-session-name: GitActionDeploymentSession
          #role-to-assume: ${{ secrets.CROSS_ACCOUNT_ROLE }}

      # Installs CDK and other prerequisites
      - name: Prerequisite Installation
        run: |
          sudo npm install -g aws-cdk@2.33.0
          cdk --version
          aws s3 ls
      - name: Run CDK diff on ${{ matrix.aws-env }}
        run: |
          npm install
          npm run build
          cdk diff 