name: Minted CDK Observability CI/CD

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGION: ap-southeast-1 # Deployment Region
  NON_PROD_AWS_KEY_ID: ${{ secrets.TOOLS_MSTA_ACCOUNT_ACCESS_KEY_ID }}
  NON_PROD_AWS_ACCESS_KEY: ${{ secrets.TOOLS_MSTA_ACCOUNT_SECRET_ACCESS_KEY }}
  PROD_AWS_KEY_ID: ${{ secrets.TOOLS_MPRO_ACCOUNT_ACCESS_KEY_ID }}
  PROD_AWS_ACCESS_KEY: ${{ secrets.TOOLS_MPRO_ACCOUNT_SECRET_ACCESS_KEY }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  plan-mdev:
    name: Run Plan
    uses: alex-woo-DevOps/helloworld/.github/workflows/reusable-plan.yml@main
    with:
      AWS-ENV: mdev
      REGION: ap-southeast-1
    secrets:
      TOOLS_ACCOUNT_ACCESS_KEY_ID: ${{ env.NON_PROD_AWS_KEY_ID }}
      TOOLS_ACCOUNT_SECRET_ACCESS_KEY: ${{ env.NON_PROD_AWS_ACCESS_KEY }}

  hold-mdev:
    runs-on: ubuntu-latest
    needs: plan-mdev
    environment:
      name: MintedCdkAlarmsStack-mdev
    steps:
      - name: Hold
        run: echo "Start Deployment..."
  
  deploy-mdev:
    name: Run Deployment
    needs: hold-mdev
    uses: alex-woo-DevOps/helloworld/.github/workflows/reusable-deploy.yml@main
    with:
      AWS-ENV: mdev
      REGION: ap-southeast-1
    secrets:
      TOOLS_ACCOUNT_ACCESS_KEY_ID: ${{ env.NON_PROD_AWS_KEY_ID }}
      TOOLS_ACCOUNT_SECRET_ACCESS_KEY: ${{ env.NON_PROD_AWS_ACCESS_KEY }}
