name: non-prod

on:
  # Do not trigger on push, otherwise $ will burn out. By default we should not Push to main branch.
  # Triggers the workflow on PR events but only for the main branch
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # vdev
  plan-vdev:
    uses: alex-woo-DevOps/helloworld/.github/workflows/reusable-plan.yml@main
    with:
      ENV: vdev
      REGION: ap-southeast-1
      STACK: " "
    secrets:
      TOOLS_ACCOUNT_ACCESS_KEY_ID: ${{ secrets.TOOLS_MSTA_ACCOUNT_ACCESS_KEY_ID }}
      TOOLS_ACCOUNT_SECRET_ACCESS_KEY: ${{ secrets.TOOLS_MSTA_ACCOUNT_SECRET_ACCESS_KEY }}
  
  hold-vdev:
    if: needs.plan-vdev.result == 'success' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: plan-vdev
    environment:
      name: vdev
    steps:
      - name: Hold
        run: echo "Start Deployment..."
  
  deploy-vdev:
    if: needs.hold-vdev.result == 'success' && github.event_name == 'push'
    needs: hold-vdev
    uses: alex-woo-DevOps/helloworld/.github/workflows/reusable-deploy.yml@main
    with:
      ENV: vdev
      REGION: ap-southeast-1
      STACK: " "
    secrets:
      TOOLS_ACCOUNT_ACCESS_KEY_ID: ${{ secrets.TOOLS_MSTA_ACCOUNT_ACCESS_KEY_ID }}
      TOOLS_ACCOUNT_SECRET_ACCESS_KEY: ${{ secrets.TOOLS_MSTA_ACCOUNT_SECRET_ACCESS_KEY }}
  # vsta
  plan-vsta:
    uses: alex-woo-DevOps/helloworld/.github/workflows/reusable-plan.yml@main
    with:
      ENV: vsta
      REGION: ap-southeast-1
      STACK: " "
    secrets:
      TOOLS_ACCOUNT_ACCESS_KEY_ID: ${{ secrets.TOOLS_MSTA_ACCOUNT_ACCESS_KEY_ID }}
      TOOLS_ACCOUNT_SECRET_ACCESS_KEY: ${{ secrets.TOOLS_MSTA_ACCOUNT_SECRET_ACCESS_KEY }}
  
  hold-vsta:
    if: needs.plan-vsta.result == 'success' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: plan-vsta
    environment:
      name: vsta
    steps:
      - name: Hold
        run: echo "Start Deployment..."
  
  deploy-vsta:
    if: needs.hold-vsta.result == 'success' && github.event_name == 'push'
    needs: hold-vsta
    uses: alex-woo-DevOps/helloworld/.github/workflows/reusable-deploy.yml@main
    with:
      ENV: vsta
      REGION: ap-southeast-1
      STACK: " "
    secrets:
      TOOLS_ACCOUNT_ACCESS_KEY_ID: ${{ secrets.TOOLS_MSTA_ACCOUNT_ACCESS_KEY_ID }}
      TOOLS_ACCOUNT_SECRET_ACCESS_KEY: ${{ secrets.TOOLS_MSTA_ACCOUNT_SECRET_ACCESS_KEY }}

